openapi: 3.0.0
info:
  title: Reminders
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /v1/reminders/:
    get:
      tags:
        - General
      summary: ' getAllReminders'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - General
      summary: createReminder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                due_date: '2022-10-17'
                text: test
                priority: high
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/reminders/filter/creation:
    get:
      tags:
        - General
      summary: filterByCreationDateRange
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
          example: '2022-10-01'
        - name: dateUntil
          in: query
          schema:
            type: string
          example: '2022-10-10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/reminders/filter/due:
    get:
      tags:
        - General
      summary: filterByDueDateRange
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
          example: '2022-12-01'
        - name: dateUntil
          in: query
          schema:
            type: string
          example: '2022-12-14'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/reminders/filter/priority/{priority}:
    get:
      tags:
        - General
      summary: filterByPriority
      parameters:
        - name: priority
          in: path
          schema:
            type: string
          required: true
          example: low
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/reminders/filter/urgent:
    get:
      tags:
        - General
      summary: getUrgentReminders
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
          example: '2022-10-10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/reminders/{reminderId}:
    get:
      tags:
        - General
      summary: getReminderById
      parameters:
        - name: reminderId
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - General
      summary: deleteReminderById
      parameters:
        - name: reminderId
          in: path
          schema:
            type: integer
          required: true
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - General
      summary: updateReminder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                due_date: '2022-12-14'
                text: updated
                priority: low
      parameters:
        - name: reminderId
          in: path
          schema:
            type: integer
          required: true
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
